name: Docker Build and Push

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: |
        docker build -t go-itinerary-api:latest .
        
    - name: Test Docker image
      run: |
        docker run -d --name test-container -p 8080:8080 go-itinerary-api:latest
        sleep 10
        curl -f http://localhost:8080/health || exit 1
        docker stop test-container
        docker rm test-container
        
    - name: Clean up
      run: |
        docker rmi go-itinerary-api:latest
